### ISSUE TITLE
Tests fail when using Ninja generator (in VS2019)

### ISSUE THREAD

**Issue by alastairUK** [approvals/ApprovalTests.cpp#55] opened 2019-12-05 16:37 UTC
CMake in VS2019 seems to default to using the Ninja generator. 

If I build with this and run the tests I get exceptions thrown.

`
1: Catch1_Tests.exe is a Catch v1.12.1 host application.
1: Run with -? for options
1:
1: -------------------------------------------------------------------------------
1: YouCanVerifyText
1: -------------------------------------------------------------------------------
1: ..\..\..\tests\Catch1_Tests\ApprovalsTests.cpp(6)
1: ...............................................................................
1:
1: ..\..\..\tests\Catch1_Tests\ApprovalsTests.cpp(6): FAILED:
1: due to unexpected exception with message:
1:   Unable to write file: ..\..\..\tests\Catch1_Tests\ApprovalsTests.
1:   YouCanVerifyText.received.txt
1:
1: ===============================================================================
1: test cases: 1 | 1 failed
1: assertions: 1 | 1 failed
`

If I use the Visual Studio 2019 generator then all seems fine

**Comment by claremacrae** [comment] 2019-12-05 18:49
Thanks for reporting this!

Is it just the Catch1 tests that fail, or do the other ones as well?

**Comment by alastairUK** [comment] 2019-12-06 11:28
It fails a number of tests not just the Catch1 ones. I think it's due to the relative path ..\..\..\tests\ not being correct for the project structure ninja creates. I did try to debug but got lost in MACROS and couldn't see anything obvious.

Will have another look later

**Comment by alastairUK** [comment] 2019-12-06 14:39
[testFails.txt](https://github.com/approvals/ApprovalTests.cpp/files/3932633/testFails.txt)

**Comment by claremacrae** [comment] 2019-12-06 16:04
I'm updating to 16.4 just now, to have a quick look...

**Comment by claremacrae** [comment] 2019-12-06 16:19
I can reproduce this, with the following steps:

1. Install Visual Studio Community 16.4
1. Open Windows > Visual Studio 2019 > "Developer Command Prompt for VS 2019"
1. cd to the location where ApprovalTests.cpp is cloned
1. `mkdir cmake-build-vs2019-ninja`
1. `cd  cmake-build-vs2019-ninja`
1. `cmake -G Ninja ..`
1. `ninja`
1. `ctest . --output-on-failure`

**Comment by claremacrae** [comment] 2019-12-06 16:35
I added this debug output to `ApprovalTests.cpp\ApprovalTests\writers\StringWriter.h`:

(std::endl delibarate...)

```c++
        std::cout << "StringWriter::write() writing to " << path << std::endl;
```

With `cmake -G Ninja` I get:

```
[ RUN      ] GoogleTestApprovalsTests.TestStreamableObject
StringWriter::write() writing to ..\examples\googletest_existing_main\GoogleTestApprovalsTests.TestStreamableObject.received.txt
unknown file: error: C++ exception with description "Unable to write file: ..\examples\googletest_existing_main\GoogleTestApprovalsTests.TestStreamableObject.received.txt" thrown in the test body.
[  FAILED  ] GoogleTestApprovalsTests.TestStreamableObject (2 ms)
```

With the "cmake -G Visual Studio 16 2019" I get:

```
[ RUN      ] GoogleTestApprovalsTests.YouCanVerifyText
StringWriter::write() writing to D:\Users\Clare\Documents\Programming\github\ApprovalTests\ApprovalTests.cpp\tests\GoogleTest_Tests\approval_tests\GoogleTestApprovalsTests.YouCanVerifyText.received.txt
[       OK ] GoogleTestApprovalsTests.YouCanVerifyText (24 ms)
```

**Comment by claremacrae** [comment] 2019-12-06 16:48
Something about building the code via Ninja in VS2019 means that `__FILE__` is giving a relative path - whereas when running via Visual Studio .sln files, `__FILE__` gives absolute paths.

Approval Tests gets the name of the current test's source file via its test framework wrapper - and the fact that there are failing tests in all our tests makes me think that the behaviour is not specific to a particular test framework:

```
D:\Users\Clare\Documents\Programming\github\ApprovalTests\ApprovalTests.cpp\cmake-build-vs2019-ninja>ctest .
Test project D:/Users/Clare/Documents/Programming/github/ApprovalTests/ApprovalTests.cpp/cmake-build-vs2019-ninja
    Start 1: Catch1_Tests
1/6 Test #1: Catch1_Tests .....................***Failed    0.14 sec
    Start 2: Catch2_Tests
2/6 Test #2: Catch2_Tests .....................***Failed    0.42 sec
    Start 3: GoogleTest_Tests
3/6 Test #3: GoogleTest_Tests .................***Failed    0.13 sec
    Start 4: DocTest_Tests
4/6 Test #4: DocTest_Tests ....................***Failed    0.10 sec
    Start 5: catch2_existing_main
5/6 Test #5: catch2_existing_main .............***Failed    0.16 sec
    Start 6: googletest_existing_main
6/6 Test #6: googletest_existing_main .........***Failed    0.12 sec

0% tests passed, 6 tests failed out of 6

Total Test time (real) =   1.20 sec

The following tests FAILED:
          1 - Catch1_Tests (Failed)
          2 - Catch2_Tests (Failed)
          3 - GoogleTest_Tests (Failed)
          4 - DocTest_Tests (Failed)
          5 - catch2_existing_main (Failed)
          6 - googletest_existing_main (Failed)
Errors while running CTest
```

**Comment by claremacrae** [comment] 2019-12-06 16:57
I wondered if this was related: [Top-level binding for working directory (aka reconcile depfile paths)](https://groups.google.com/forum/#!topic/ninja-build/yJvs7u0n2iA)

I tried using a full path when generating the ninja files - in a different directory - 

```
cmake -G Ninja D:\Users\Clare\Documents\Programming\github\ApprovalTests\ApprovalTests.cpp
```

I still got the same test failures, this, with relative paths in the `__FILE__` output to `cout`.

**Comment by claremacrae** [comment] 2019-12-06 16:58
I wondered about adding to the Approval Tests code that works out source file names, to get the current working directory, and prepend it to the relative path...

However, I think that is going to be problematic, as the `__FILE__` string is generated at compile time, and I *think* that there is no guarantee that the cwd at run-time will be the same as that at compile time???

**Comment by claremacrae** [comment] 2019-12-06 17:04
I've asked in the build-systems channel in include-cpp Discord... will report back here if anything useful is mentioned...

**Comment by alastairUK** [comment] 2019-12-06 17:29
I think you can hack this by passing /FC (https://docs.microsoft.com/en-us/cpp/build/reference/fc-full-path-of-source-code-file-in-diagnostics?view=vs-2019) to CXXFLAGS

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /FC") 

This seems to work on a very quick test for Ninja build I think

Would need to add something to make it specific to those builds on MSVC I guess.

Sure  there is a better way of addressing this!

**Comment by claremacrae** [comment] 2019-12-06 17:35
Thanks - yes, I was just testing the replies I got on Discord:

melak47:

- @ClareMacrae you can use /FC to make MSVC emit the full path in diagnostics, and __FILE__ https://docs.microsoft.com/en-us/cpp/build/reference/fc-full-path-of-source-code-file-in-diagnostics?view=vs-2019

Me:

- Wow - thank you very much. So we could customise our CMake file for the Approval Tests library, to add this option for Visual Studio builds, so that our own tests would pass...
- And for anyone who downloaded our single header release, and used it with Ninja and VS2019, they would still have to know to add this option...
- And we could add a check in the code that detected if there was a problem with the file path, and if so, wrote out some helpful text that pointed people to something like an FAQ

...

melak47:

- you could maybe even make a check at compile time, like
```c++
#ifdef _MSC_VER
static_assert(__FILE__[1] == ':', "Please compile with /FC, see <link> for details");
#endif 
```

- (though I dunno if this might break if you try giving the compiler UNC paths to files or something :D)
- if you explicitly tell cmake to emit the /FC compiler option, it should work fine even with ninja
- try something like

```cmake
target_compile_options(your_library PUBLIC $<$<CXX_COMPILER_ID:MSVC>:/FC>)
```

**Comment by claremacrae** [comment] 2019-12-06 17:53
Adding this ...

```cmake
target_compile_options(${PROJECT_NAME} INTERFACE $<$<CXX_COMPILER_ID:MSVC>:/FC>)
```

to the end of `ApprovalTests/CMakeLists.txt` does indeed fix all the tests with Ninja

**Comment by claremacrae** [comment] 2019-12-06 18:00
My current understanding of the possible actions for this are:

* [ ] Add `/FC` arg for MSVC compilation
* [ ] Add an FAQ for this - or something in troubleshooting
* [ ] Add static_assert to detect the error in windows - if we can get it working with UNC paths too
* [ ] Add some code that a check in ApprovalTestNamer.h - in TestName::setFileName() to check whether the given source file does not exist - and probably point to the URL write-up of this problem

**Comment by claremacrae** [comment] 2019-12-06 18:25
This may be useful:
https://gitlab.kitware.com/cmake/cmake/issues/18261

**Comment by claremacrae** [comment] 2019-12-06 18:37
And this:
https://gitlab.kitware.com/cmake/cmake/merge_requests/2306

**Comment by claremacrae** [comment] 2019-12-19 23:03
When building in Visual Studio 2019 with the `clang_cl_x64` toolset, in a project opened in Visual Studio via 'Open Folder', we get the same errors like:

```
-------------------------------------------------------------------------------
YouCanVerifyCombinationsOf3WithAuto
-------------------------------------------------------------------------------
..\..\..\tests\Catch2_Tests\documentation\CombinationsSampleCode.cpp(37)
...............................................................................

..\..\..\tests\Catch2_Tests\documentation\CombinationsSampleCode.cpp(37): FAILED:
due to unexpected exception with message:
  Unable to create directory: ..\..\..\tests\Catch2_Tests\documentation\
  approval_tests\
```

The difference when using the clang-cl compiler is that the `/FC` command line argument is not supported - possibly something due to deterministic builds - see https://reviews.llvm.org/D63648

I also learned today that VS2019 with "Open Folder" and CMake builds now puts outputs in to folders such as:

`ApprovalTests.cpp\out\build\x64-Clang-Release`

And since this is inside the source directory, relative paths to the source code are used... hence all the `..\..\..\`

So maybe we have to start doing something like combining the Current Working Directory when the tests are run with the absolute path of the working directory???

**Comment by claremacrae** [comment] 2019-12-19 23:04
> So maybe we have to start doing something like combining the Current Working Directory when the tests are run with the absolute path of the working directory???

If this could work, then we wouldn't need to mess around with `/FC` which would be better for user.

**Comment by claremacrae** [comment] 2019-12-19 23:14
Example location of .exe:

`D:\Users\Clare\Documents\Programming\github\ApprovalTests\ApprovalTests.cpp\out\build\x64-Clang-Release\tests\Catch2_Tests\Catch2_Tests.exe`

What I don't know is what the current working directory is, when that program is run.

**Comment by claremacrae** [comment] 2019-12-20 20:56
We found that the working directory was this:

```"D:\\Users\\Clare\\Documents\\Programming\\github\\ApprovalTests\\ApprovalTests.cpp\\out\\build\\x64-Debug\\examples\\catch2_existing_main"```

So I think that 5 `..\` are required to get to the source, not the 3 that are contained in `__FILE__``

**Comment by claremacrae** [comment] 2019-12-21 00:20
Thanks for reporting this, @alastairUK 

We've fixed this with the Visual C++ compiler by adding `/FC` in the ApprovalTests.cpp project - and for everyone who uses this as a sub-project.

We've also added nicer error messages in case this happens to any one - that point to:

https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/TroubleshootingMisconfiguredBuild.md#top

Note that we don't have a solution for when the compiler is clang-cl - other than than the user moving to completely out-of-source builds...

Closing this, as we hope that this is good enough - please do let us know if there are still any problems.

**Closed by claremacrae** 2019-12-21 00:20 UTC
Labels: bug
